# Generated by Django 4.1.2 on 2022-10-27 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameName', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('LB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darbiniai_app.leaderboard')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
