# Generated by Django 4.1.2 on 2022-11-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0002_entry_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='username',
        ),
    ]
