# Generated by Django 4.1.3 on 2022-12-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0002_entry_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.ImageField(default=None, upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='entry',
            name='username',
        ),
    ]
