# Generated by Django 4.1.2 on 2022-12-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0002_remove_game_file_remove_game_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='file',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(default=0, upload_to='media'),
            preserve_default=False,
        ),
    ]
