# Generated by Django 4.1.3 on 2022-12-15 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0003_game_remove_entry_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(default=None, upload_to='icons/'),
        ),
    ]
