# Generated by Django 4.1.3 on 2022-11-18 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0004_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='file',
        ),
    ]
