# Generated by Django 4.1.3 on 2022-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0004_alter_game_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='file',
            field=models.FileField(default=None, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(default=None, upload_to='files'),
        ),
    ]
