# Generated by Django 4.1.3 on 2022-12-15 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0005_game_file_alter_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
