# Generated by Django 4.1.3 on 2022-11-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0005_remove_game_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='icon',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
