# Generated by Django 4.1.3 on 2022-12-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0007_alter_game_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='icon',
            field=models.ImageField(max_length=100000, upload_to='files'),
        ),
    ]
