# Generated by Django 4.1.3 on 2022-12-15 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0012_alter_game_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='file',
        ),
    ]
