# Generated by Django 4.1.3 on 2022-12-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0013_remove_game_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='file',
            field=models.FileField(default=None, upload_to='media'),
        ),
    ]
