# Generated by Django 4.1.3 on 2022-12-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darbiniai_app', '0014_game_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='file',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
